### ISSUE TITLE
Suggestion: Curb unecesary and innacurate projectile catalog error

### ISSUE THREAD

**Issue by Nebby1999** [risk-of-thunder/RoR2BepInExPack#4]
int num = 256;
		if (projectilePrefabs.Length > num)
		{
			Debug.LogErrorFormat("Cannot have more than {0} projectile prefabs defined, which is over the limit for {1}. Check comments at error source for details.", num, typeof(byte).Name);
			for (int j = num; j < projectilePrefabs.Length; j++)
			{
				Debug.LogErrorFormat("Could not register projectile [{0}/{1}]=\"{2}\"", j, num - 1, projectilePrefabs[j].name);
			}
		}

These lines of code where relevant prior to the Anniversary update of risk of rain 2, they've not been removed on SOTV and can cause confusion among users and inexperienceed modders.

I supose an option is to ILHook the ProjectileCatalog.SetProjectilePrefabs() method and skip over the first if statement, or change it so it always equals to false.

**Comment by Crypto-Spartan** [comment]
@Nebby1999 would you mind explaining this a bit more? Found this after googling, I see this error message currently, and we've been disabling mods to get under the limit. Are you saying that after SOTV, the limit is increased? (I'm guessing at least to 65,535 if 2 bytes are used)

**Comment by xiaoxiao921** [comment]
You can ignore the log, the actual limit is much biggeri can't check right now but I think it's an int now

**Comment by Crypto-Spartan** [comment]
Awesome, thank you!

**Comment by Darkmega18** [comment]
oh nice. so, false positive error then?

**Comment by Nebby1999** [comment]
@Darkmega18 it's indeed a false positive

Fixing this would still be nice tho, it's a bit annoying but harmless

**Comment by Darkmega18** [comment]
alrighty. I got here through google too cause I spied them in the console and got concerned. but I figured my game was still working so didn't know how bad if at all it was. lol

**Comment by xiaoxiao921** [comment]
Fixed by #13
