### ISSUE TITLE
Prismatic Trial Button kills controller inputs when hidden

### ISSUE THREAD

**Issue by xiaoxiao921** [risk-of-thunder/RoR2BepInExPack#8]
Text taken partially from Zarphus who reported the issue, 
prismatic trials being absent is intentional when modded
the issue is that by default, the option first highlighted in that menu for the gamepad inputs to scroll up and down the list, is gone as a result. this puts the cursor nowhere for gamepad users, and they cannot navigate that menu or select ANY mode.

**Comment by KingEnderBrine** [comment]
A year ago I fixed it as part of R2API, https://github.com/risk-of-thunder/R2API/pull/282. Seems like it was lost when moving fixes and stuff from R2API to RoR2BepInExPack

**Comment by KingEnderBrine** [comment]
Ah, yes, Hopoo removed `DisableIfGameModded` component from the button, so this hook was removed entirely https://github.com/risk-of-thunder/RoR2BepInExPack/commit/6994a2cd5eff368f6ffae34b11ca7cc3982cd4c4

**Comment by xiaoxiao921** [comment]
Closed by #9
